name: Google Cloud Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: empirical-axon-438202-p3
          service_account_key: 
            type: "service_account"
            project_id: "empirical-axon-438202-p3"
            private_key_id: "19d84c0b2139103636c4e04b310b1e6cff1fb4b0"
            private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC15aCnrnq2aXap\nHN1FCtfndfTNUDyCLUDxAi9O8OO8qV2uhZPg9SiOv1nAXtC/E/ELU7os8I+umUCg\nyUwVxH6+yClk/lWQPe7BYLpBFBtY2kFDvjj2hduHDwYykXRfla9GV5/GKcY6RWB8\nAWhBmtSh+XU1aISLmYcY2hpuyyWWyMeHdA3kFG6jtXoBPVGJOQdX/f/kOKCaDPmq\nklpC1dW0gHWl5TfCJmYb2g+ZtIeU9PFsWfy4jgaCGXGuix1Jlv/0bCMPdWV5hN5r\nQH/TK3d5X+rDqedV159BVH7KYmWkKVYscrP6yMj0mAuWIx8MystaPp9WWWTFfTEe\n8W94pbLXAgMBAAECggEABvdMJO/P1O7gCPpJLQzibNj9xDkiQBgB6IOdZ91eKLT8\nbfkWoI2y/RiDPuntU6FXYLLW/+6XNL1mFgzveYFExgNTYSyY/ppTQPD2i78nNvVm\nJ3Uq/aHttik9+FoisKBtDc7AQy4JYI+UnNskRihATr2yHpap8NCzNaFF/t/lHiDy\nBI4VreFg15UR+op8Y0adwvp8+AlIwK2zNKULLUDb0apCXes3P8KFIUiJafWS6vVc\nm0YmeLzZDEPJAnYHDdnveMmK7+i1SHZVZlPLcgmj5r/bIwUFpvmytsZtGuQY8sbl\nBVrTHRkpUpJw18UfpbIhUd+xXyWEWXYyEPvxVxcLRQKBgQDAkgfysoOOAWdyLJe4\nEY6Fctbxl/dXawjGUTMVeaNMKWtjWoOX49LYnpLPEQ3Xx9/MhnaUG05AF+T5jAV0\nIPwdJBZoSk7VRdz6n/71LawcSZJE/VR3mCOb6p6SNFjR5+Uic2c43XRknMRvl0J1\nGVnUxdlurPASoMzvx08b1sUs1QKBgQDxz5ZYBcBnObbG8rTFRCf/AQYU5CxlzFIF\nPpbKj6Hpn62XJZC7Fm6pX0G0//T7vGTvP/GuMFmNN069b1cl1Jwt1AW4/XTG2xMw\njHS3mBNuQTgG4+oH/dMe0CjwppMWfmLbNqNcQDPCqww6NVB64UHWkZJvfg5oBjQI\n6yynrQ7G+wKBgDg5qwZqpsyMjmagrH+66JEAMdACXd5xSvOUe8TWah5vrYIpyGhN\nxZ8n1ZeN1CvfmPF/hRnDSzqdf2Z5QpJgmxvrEHvMzm2o41dt5aQyfKEZvhJUoRf2\nHNeGTlxD2ncXLSi85zOMPVKvDw/B606DY14jklOlPMdDmfKcj/WB5LotAoGASfD4\nQCJCG06CnYNJ06hrsoZVnb3H9bjsu73PzlDtacryAe3yu8K4RAJkzTwXZYLOOnqL\nJICUYaIv6a1KML86oqjatx6JvuTukUHhzuIpzuUShMjcn2T2Uc3FNxE4mQA8qlui\nyGq5aSV0r7ftzCVlRH9vD7i0HwsGjlObbAp3IlECgYBniq+HcfpWoC1pxAFLTBRz\nh9O8VHyEVDbsyAjrB9hgxpiO//iwDTNerUuis1YUuLdWyqvxWKH/G+YAWUBatDft\nutH0Rj1CJ4LyKEB65ogZqYyl8PaBzmdCWN2EuNb91Rl9GCCupxcSQ7do6Dw969r4\nMyT1iHReIl4I+MhwzQ56fQ==\n-----END PRIVATE KEY-----\n"
            client_email: "868239089963-compute@developer.gserviceaccount.com"
            client_id: "101585248209000472677"
            auth_uri: "https://accounts.google.com/o/oauth2/auth"
            token_uri: "https://oauth2.googleapis.com/token"
            auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
            client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/868239089963-compute%40developer.gserviceaccount.com"
            universe_domain: "googleapis.com"
          export_default_credentials: true
            
      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml
